const RspyList = {
    /* 监控信息配置 */
    SpyList: [
        //------------------------------------------------------------------
        //9R系
        {
            /* 任务名 确保任务名唯一性,因为id根据任务名计算生成*/
            Name: "9R知识超人_wx",
            /* 执行的脚本名 */
            Script: "9Rebels_jdmax/jd_wxKnowledgeActivity.js",
            /* 监听变量 */
            ListenEnv: ["jd_wxKnowledgeActivity_activityUrl", "jd_wx_Knowledge", "jd_wx_knowledge_id"],
            /* 转换变量 */
            SetEnv: {
                jd_wx_Knowledge: "jd_wxKnowledgeActivity_activityUrl",
                jd_wx_knowledge_id: "jd_wxKnowledgeActivity_activityUrl",
            },
            /* 超时退出 (秒)*/
            TimeOut: 0,
            /* 间隔时间(秒) */
            Interval: 0,
            /* 运行面板 0 代表 面板管理中的第一个容器 以此类推 */
            RunPanel: [0],
            //RunPanel: [0, 1, 2],
            /* 禁用任务 */
            Disable: false,
        },
        {
            Name: "9R知识超人_100",
            Script: "9Rebels_jdmax/jd_lzkj_loreal_know.js",
            ListenEnv: ["jd_lzkj_loreal_know_url", "jd_lzkj_know_url"],
            SetEnv: {
                jd_lzkj_know_url: "jd_lzkj_loreal_know_url",
            },
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R签到监控_100v2",
            Script: "9Rebels_jdmax/jd_lzkj_v2_sign.js",
            ListenEnv: ["jd_lzkj_v2_sign_url"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R签到监控_wx",
            Script: "9Rebels_jdmax/jd_wx_shopSign.js",
            ListenEnv: ["jd_wx_shopSign_activityUrl"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R福袋_wx",
            Script: "9Rebels_jdmax/jd_wxUnPackingActivity.js",
            ListenEnv: ["jd_wxUnPackingActivity_activityId"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R每日抢_wx",
            Script: "9Rebels_jdmax/jd_wx_daily.js",
            ListenEnv: ["jd_wx_daily_url"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R每日抢_100",
            Script: "9Rebels_jdmax/jd_lzkj_loreal_dailyGrabs.js",
            ListenEnv: ["jd_lzkj_loreal_dailyGrabs_url"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R抽奖_100v2",
            Script: "9Rebels_jdmax/jd_lzkj_v2_draw.js",
            ListenEnv: ["jd_lzkj_v2_draw_url"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R完善_100",
            Script: "9Rebels_jdmax/jd_lzkj_loreal_perfectInfo.js",
            ListenEnv: ["jd_lzkj_loreal_perfectInfo_url"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R完善_100v2",
            Script: "9Rebels_jdmax/jd_lzkj_v2_perfectInfo.js",
            ListenEnv: ["jd_lzkj_v2_perfectInfo_url"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R完善_wx",
            Script: "9Rebels_jdmax/jd_wx_completeInfoActivity.js",
            ListenEnv: ["jd_wx_completeInfoActivity_activityUrl"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R完善_jinggeng",
            Script: "9Rebels_jdmax/jd_jinggeng_perfectInformation.js",
            ListenEnv: ["jd_jinggeng_perfectInformation_url"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R生日_100v2",
            Script: "9Rebels_jdmax/jd_lzkj_v2_birthday.js",
            ListenEnv: ["jd_lzkj_v2_birthday_url"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R抽奖_100",
            Script: "9Rebels_jdmax/jd_lzkj_loreal_draw.js",
            ListenEnv: ["jd_lzkj_loreal_draw_url", "jd_lzkj_draw_url"],
            SetEnv: {
                jd_lzkj_draw_url: "jd_lzkj_loreal_draw_url",
            },
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R抽奖_gzsl",
            Script: "9Rebels_jdmax/jd_gzsl_lottery.js",
            ListenEnv: ["jd_gzsl_lottery_url"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R组队_wx",
            Script: "9Rebels_jdmax/jd_wxTeam.js",
            ListenEnv: ["jd_wxTeam_activityUrl"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R盖楼_jinggeng",
            Script: "9Rebels_jdmax/jd_jinggeng_floor.js",
            ListenEnv: ["jd_jinggeng_floor_url"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R兑换_E卡",
            Script: "9Rebels_jdmax/jd_pointExgECard.js",
            ListenEnv: ["jd_pointExgECard_activityUrl"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R兑换_京豆",
            Script: "9Rebels_jdmax/jd_pointExgBeans.js",
            ListenEnv: ["jd_pointExgBeans_activityUrl"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R兑换_实物",
            Script: "9Rebels_jdmax/jd_pointExgShiWu.js",
            ListenEnv: ["jd_pointExgShiWu_activityUrl"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R兑换_红包",
            Script: "9Rebels_jdmax/jd_pointExgHb.js",
            ListenEnv: ["jd_pointExgHb_activityUrl"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R关注商品_100",
            Script: "9Rebels_jdmax/jd_lzkj_loreal_followGoods.js",
            ListenEnv: ["jd_lzkj_loreal_followGoods_url"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R关注店铺_100",
            Script: "9Rebels_jdmax/jd_lzkj_loreal_lkFollowShop.js",
            ListenEnv: ["jd_lzkj_loreal_lkFollowShop_url"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R关注_arg",
            Script: "9Rebels_jdmax/jd_drawShopGift.js",
            ListenEnv: ["BEAN_FOLLOW"],
            SetEnv: {
                BEAN_FOLLOW: "jd_drawShopGift_argv",
            },
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R翻牌_url",
            Script: "9Rebels_jdmax/jd_sendbeans.js",
            ListenEnv: ["jd_sendbeans_url"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R加购_100",
            Script: "9Rebels_jdmax/jd_lzkj_loreal_cart.js",
            ListenEnv: ["jd_lzkj_loreal_cart_url"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "SM加购_100",
            Script: "SuperManito_cishanjia_main/jd_lzkj_cart.js",
            ListenEnv: ["jd_lzkj_cart_url"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "SM加购_wx",
            Script: "SuperManito_cishanjia_main/jd_wxCollectionActivity.js",
            ListenEnv: ["jd_wxCollectionActivity_activityUrl"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R加购_txzj",
            Script: "9Rebels_jdmax/jd_txzj_cart_item.js",
            ListenEnv: ["jd_cart_item_activityUrl"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R分享_wx",
            Script: "9Rebels_jdmax/jd_wxShareActivity.js",
            ListenEnv: ["jd_wxShareActivity_activityId"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: true,
        },
        {
            Name: "9R粉丝互动_wx",
            Script: "9Rebels_jdmax/jd_wxFansInterActionActivity.js",
            ListenEnv: ["jd_wxFansInterActionActivity_activityId"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R抽奖_protask",
            Script: "9Rebels_jdmax/jd_pro_lottery_task.js",
            ListenEnv: ["jd_pro_lottery_task_id"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R抽奖_prolott",
            Script: "9Rebels_jdmax/jd_pro_lottery.js",
            ListenEnv: ["jd_pro_lottery_id"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "SM分享_txzj",
            Script: "9Rebels_jdmax/jd_txzj_collect_item.js",
            ListenEnv: ["jd_collect_item_activityUrl"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "SM关注_txzj",
            Script: "9Rebels_jdmax/jd_txzj_collect_shop.js",
            ListenEnv: ["jd_collect_shop_activityUrl"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R兑换_jinggeng",
            Script: "9Rebels_jdmax/jd_jinggeng_exchangeActDetail.js",
            ListenEnv: ["jd_jinggeng_exchangeActDetail_url"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "SM抽奖_txzj",
            Script: "9Rebels_jdmax/jd_txzj_lottery.js",
            ListenEnv: ["jd_lottery_activityUrl"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R->环境直播_live",
            Script: "feverrun_my_scripts/jd_live_lottery.js",
            ListenEnv: ["jd_live_ids"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "9R入会_shopcard",
            Script: "9Rebels_jdmax/jd_opencard_gift.js",
            ListenEnv: ["jd_opencard_venderId"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        //------------------------------------------------------------------
        //环境系
        {
            Name: "环境盖楼_100",
            Script: "feverrun_my_scripts/jd_lzkj_10047_glyl.js",
            ListenEnv: ["jd_lzkj_10047_glyl_Ids"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        //------------------------------------------------------------------
        //J系
        {
            Name: "Je签到监控_100",
            Script: "Jejz168_BoredPlay/interact_sign_jk_Jejz.js",
            ListenEnv: ["INTERACT_SIGN_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "Je签到监控_txzj",
            Script: "Jejz168_BoredPlay/txzj_Sign_jk_Jejz.js",
            ListenEnv: ["TXZJ_SIGN_JK_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "Je签到监控_hdb",
            Script: "Jejz168_BoredPlay/hdb_SignIn_jk_Jejz.js",
            ListenEnv: ["HDB_SIGNIN_JK_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "Je签到监控_10023",
            Script: "Jejz168_BoredPlay/interact_daySign_jk_Jejz.js",
            ListenEnv: ["INTERACT_DAY_SIGN_JK_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "Je签到监控_jinggeng",
            Script: "Jejz168_BoredPlay/jinggeng_showSign_jk_Jejz.js",
            ListenEnv: ["JINGGENG_SHOW_SIGN_JK_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "Je红包_100",
            Script: "Jejz168_BoredPlay/interact_hbCount_Jejz.js",
            ListenEnv: ["INTERACT_HBCOUNT_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "Je关注_gzsl",
            Script: "Jejz168_BoredPlay/gzsl_contactWare_Jejz.js",
            ListenEnv: ["GZSL_CONTACT_WARE_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: true,
        },
        {
            Name: "Je分享_txzj",
            Script: "Jejz168_BoredPlay/txzj_ShareNew_Jejz.js",
            ListenEnv: ["TXZJ_SHARE_NEW_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        //------------------------------------------------------------------
        //M系
        {
            Name: "M老虎机抽奖_wx&100",
            Script: "walle1798_EVE/m_jd_wx_centerDraw.js",
            ListenEnv: ["M_WX_CENTER_DRAW_URL", "jd_drawCenter_activityId"],
            SetEnv: {
                jd_drawCenter_activityId: "M_WX_CENTER_DRAW_URL",
            },
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "M加购有礼V1_wx&100&hdb&gzsl&jinggeng",
            Script: "walle1798_EVE/m_jd_wx_addCart.js",
            ListenEnv: ["M_WX_ADD_CART_URL", "LOTTERY_SHOP_DRAW_JK_URL"],
            SetEnv: {
                LOTTERY_SHOP_DRAW_JK_URL: "M_WX_ADD_CART_URL",
            },
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: true,
        },
        {
            Name: "M购物车锦鲤_wx&100&jingyun",
            Script: "walle1798_EVE/m_jd_wx_cartKoi.js",
            ListenEnv: ["M_WX_CARTKOI_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "M幸运抽奖_wx&100&jingyun",
            Script: "walle1798_EVE/m_jd_wx_luckDraw.js",
            ListenEnv: ["M_WX_LUCK_DRAW_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "M无线关注_wx&100",
            Script: "walle1798_EVE/m_jd_wx_shopGift.js",
            ListenEnv: ["M_WX_SHOP_GIFT_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "M邀请有礼_jinggeng",
            Script: "walle1798_EVE/m_jd_wx_showInviteJoin.js",
            ListenEnv: ["M_JINGGENG_INVITE_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "M关注抽奖_wx&100&jinggeng",
            Script: "walle1798_EVE/m_jd_wx_followDraw.js",
            ListenEnv: ["M_WX_FOLLOW_DRAW_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "M分享有礼_100",
            Script: "walle1798_EVE/m_jd_wx_share.js",
            ListenEnv: ["M_WX_SHARE_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "M通用开卡_lzdz&jinggeng&szxyun",
            Script: "walle1798_EVE/m_jd_wx_opencard_m.js",
            ListenEnv: ["M_WX_OPENCARD_M_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "M组队瓜分_wx&100&jinggeng&hdb",
            Script: "walle1798_EVE/m_jd_wx_team.js",
            ListenEnv: ["M_WX_TEAM_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "M无线游戏_wx&100",
            Script: "walle1798_EVE/m_jd_wx_game.js",
            ListenEnv: ["M_WX_GAME_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: true,
        },
        {
            Name: "M等级/生日礼包_wx",
            Script: "walle1798_EVE/m_jd_wx_levelBirth.js",
            ListenEnv: ["M_WX_LEVEL_BIRTH_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "M入会有礼_shopcard",
            Script: "walle1798_EVE/m_jd_open_card.js",
            ListenEnv: ["M_OPEN_CARD_ARGV"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: true,
        },
        {
            Name: "M完善有礼_wx&100&jinggeng",
            Script: "walle1798_EVE/m_jd_wx_completeDraw.js",
            ListenEnv: ["M_WX_COMPLETE_DRAW_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "M积分兑换_wx&100&jingyun",
            Script: "walle1798_EVE/m_jd_wx_pointDraw.js",
            ListenEnv: ["M_WX_POINT_DRAW_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: true,
        },
        {
            Name: "M知识超人_wx&100",
            Script: "walle1798_EVE/m_jd_wx_knowledge.js",
            ListenEnv: [
                "jd_wxKnowledgeActivity_activityUrl",
                "jd_wx_Knowledge",
                "jd_wx_knowledge_id",
                "M_WX_KNOWLEDGE_URL",
                "jd_lzkj_loreal_know_url",
                "jd_lzkj_loreal_know_url",
                "jd_lzkj_know_url",
            ],
            SetEnv: {
                jd_wxKnowledgeActivity_activityUrl: "M_WX_KNOWLEDGE_URL",
                jd_wx_Knowledge: "M_WX_KNOWLEDGE_URL",
                jd_wx_knowledge_id: "M_WX_KNOWLEDGE_URL",
                M_WX_KNOWLEDGE_URL: "M_WX_KNOWLEDGE_URL",
                jd_lzkj_loreal_know_url: "M_WX_KNOWLEDGE_URL",
                jd_lzkj_loreal_know_url: "M_WX_KNOWLEDGE_URL",
                jd_lzkj_know_url: "M_WX_KNOWLEDGE_URL",
            },
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: true,
        },
        {
            Name: "M读秒手速_wx",
            Script: "walle1798_EVE/m_jd_wx_secondDraw.js",
            ListenEnv: ["M_WX_SECOND_DRAW_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: "M分享福袋_wx",
            Script: "walle1798_EVE/m_jd_wx_unPackDraw.js",
            ListenEnv: ["M_WX_UNPACK_DRAW_URL"],
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        //以下给出几个示例
        /*{
            Name: '无线',
            Script: 'jd_task_wuxian.js',
            ListenEnv: [
                'jd_task_wuxian_custom',
                'jd_task_hudong_custom',
                'LUCK_DRAW_URL',
            ],
            SetEnv: {
                jd_task_hudong_custom: 'jd_task_wuxian_custom',
                LUCK_DRAW_URL: 'jd_task_wuxian_custom',
            },
            TimeOut: 50,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: '集卡',
            Script: 'jd_task_jika.js',
            ListenEnv: ['M_WX_COLLECT_CARD_URL', 'jd_wxCollectCard_activityId'],
            SetEnv: {
                M_WX_COLLECT_CARD_URL: 'jd_task_jika_custom',
                jd_wxCollectCard_activityId: 'jd_task_jika_custom',
            },
            TimeOut: 80,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },
        {
            Name: '组队',
            Script: 'jd_task_cjzlzd.js',
            ListenEnv: ['jd_task_cjzlzd_custom', 'jd_cjhy_activityId', 'jd_zdjr_activityId', 'M_WX_TEAM_URL'],
            SetEnv: {
                jd_cjhy_activityId: 'jd_task_cjzlzd_custom',
                jd_zdjr_activityId: 'jd_task_cjzlzd_custom',
                M_WX_TEAM_URL: 'jd_task_cjzlzd_custom',
            },
            TimeOut: 0,
            Interval: 0,
            RunPanel: [0],
            Disable: false,
        },*/
    ],
    /* 监控列表 */
    ListenList: [
        {
            Name: "",
            Id: "-",
        },
        {
            Name: "",
            Id: "",
        },
    ],
    /* 设置 管理员发送https的Url解析模式,  ''或者直接删除这一行为自动解析，spyjx:'j', 则发url链接时需要以j开头才会解析*/
    spyjx: "",
    //非静默触发消息多少秒撤回 0不撤回
    delMsgWaitTime: 10,
    //静默功能  默认false,会在监听到消息的地方回复监听结果 true则推送到静默推送设置的地方
    Taboo: true,
    TabooOriginalMsg: false /* 静默后推送的消息是否显示触发消息 */,
    //1 禁用任何日志输出 改为true后,不会向社交平台推送任何消息,且2 3开关失效 控制台除外
    DisableAllLogs: false,
    //2 禁用错误日志输出 改为true后,不会向社交平台推送任何错误消息 控制台除外
    DisableErrLogs: false,
    //3 禁用正常运行日志输出 改为true后,不会向社交平台推送任何任务运行成功的消息 控制台除外
    DisableRunLogs: false,
    //4 禁用控制台日志 改为true后,控制台不会显示任何消息
    DisableConsoleLog: false,
    //队列模式 1先进先出  2先进后出  其他值均视为 先进先出
    ListMode: 2,
    /* 运行日志输出位置,例如错误运行日志/任务运行成功等日志,只能设置1个 */
    runLogsInfo: {
        platform: "", //发送平台
        toGroupOrUser: "", //通知类型,个人userId //群groupId
        Id: "-", //个人id 或群id
    },
    /* 静默后监控结果输出位置  可填多个*/
    TabooLogsInfo: [
        // 	{
        // 	platform: "HumanTG",
        // 	toGroupOrUser: "groupId",   //通知类型,个人userId //群groupId
        // 	Id: "-1001744932665"
        // },
        {
            platform: "", //发送平台
            toGroupOrUser: "", //通知类型,个人userId //群groupId
            Id: "-", //个人id 或群id
        },
    ],
};

module.exports = {
    RspyList,
};
